name: animinu
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # firebase
  firebase_core: ^2.16.0
  firebase_analytics: ^10.5.0
  firebase_database: ^10.2.6
  firebase_auth: ^4.10.0

  # state
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0

  shared_preferences: ^2.2.1

  # anime info
  myanimelist_api:
    git:
      url: https://github.com/yurtemre7/MyAnimeList-API.git
      ref: master

  dynamic_color: ^1.6.7
  efficient_autocomplete_formfield: ^0.3.2+1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg